Use U7open_in() to check if files exist
exult/exult pull request #182
Opened 2022-04-18 05:23 UTC by ceckak

A susbsequent patch will introduce new file access abstractions which do not support calling `stat()`.  Switch to speculatively opening files for reading to test if they exist as a preliminary cleanup step.

2022-04-19 17:30 UTC, Dragon-Baroque commented
Please, in `files/utils.cc` why do you need to test whether `istream_factory` is non NULL in `U7Remove` ?

2022-04-19 18:00 UTC, ceckak commented
> Please, in `files/utils.cc` why do you need to test whether `istream_factory` is non NULL in `U7Remove` ?

You're talking about line 387?
```
if (in && in->good() && !in->fail()) {
```

I don't recall if I had a concrete case where I needed it, but in theory, `istream_factory()` could fail and return `nullptr`, so I think I was just being defensive here to avoid a potential crash.  This is a `void` function so I can't propagate an error, but I could log an error or throw an exception if you prefer.

2022-04-19 18:09 UTC, Dragon-Baroque commented
No, I was refering to
```
	if (istream_factory) {
		in = istream_factory(name.c_str(), std::ios_base::in);
	} else {
		in = std::make_unique<std::ifstream>(name.c_str(), std::ios_base::in);
	}
```

2022-04-20 00:07 UTC, ceckak commented
> No, I was refering to
> 
> ```
> 	if (istream_factory) {
> 		in = istream_factory(name.c_str(), std::ios_base::in);
> 	} else {
> 		in = std::make_unique<std::ifstream>(name.c_str(), std::ios_base::in);
> 	}
> ```

Ah - I see.  This was introduced to address some early feedback I got from @DominusExult.  I originally was depending on the SDL-backed streams by default, and this forced all the standalone utilities that interact with files to take an SDL dependency.  To address that, I introduced the factory so that the SDL dependency can be injected by `exult.cc`, and if no factory has been provided, I fall back to standard file access.  This enables all the standalone utilities to continue to work without having to provide a factory or take an SDL dependency.

2022-04-23 13:32 UTC, marzojr requested changes

2022-04-23 13:32 UTC, marzojr commented
Other than those, looks good.

2022-04-23 13:35 UTC, marzojr commented
Hm. These notes should be for #181, for some reason the notifications in GH were on the wrong order.

2022-04-23 21:21 UTC, ceckak commented
> Other than those, looks good.

Thanks for reviewing.  Suggested whitespace changes are implemented in #181

2022-04-24 11:17 UTC, marzojr approved these changes

2022-04-24 11:18 UTC, marzojr approved these changes

2022-04-24 11:28 UTC, merged