Background/ambient sfx music tracks are less annoying
exult/exult pull request #503
Opened 2024-04-20 22:17 UTC by DominusExult

- bg tracks are disabled for the FMOpl driver, even though these were used in the original. They are way too noisy.
- DangerNear is now playing for all drivers
- nighttime bg track is disabled as it is too noisy
- bg sfx waves are playing on nighttime for all drivers
- bg sfx wave tracks are being played on SI as well

Fixes #498

2024-04-28 16:31 UTC, marzojr commented on gamewin.cc
> +					/*if (play_bg_tracks)
I disagree with disabling this, at least like this. Maybe add a config option to disable it instead?

2024-04-28 16:35 UTC, marzojr requested changes

2024-04-28 16:35 UTC, marzojr commented on gamewin.cc
> +	if (player && !play_bg_tracks && player->get_current_track() == 6) {
Please add the check for track 7 anyway and remove/edit the comment. That way, if we later decide to uncomment the track 7 code (or if the config option I suggest is added), the code will work without needing further changes.

2024-04-28 16:35 UTC, marzojr commented on gamewin.cc
> +						tracknum  = Audio::game_music(7);*/
I disagree with disabling this, at least like this. Maybe add a config option to disable it instead?

2024-04-28 16:56 UTC, DominusExult commented
Re-enabled the Nighttime track.
Before this is ready to be merged, @wench mentioned in #498 that his jukebox egg looping fix also fixes the bee cave outside of this.
```
// Don't override bee cave music with dungeon music.
			const bool notbees = !GAME_BG || curr_track != 54;
if (curr_track == -1 || gwin->is_bg_track(curr_track)
				|| (((currentstate == Dungeon && notbees)
					 || currentstate == DangerNear)
					&& !is_combat_music(curr_track))) {
```

And possibly this TODO, right?
```
// ++++ TODO: Need to come up with a way to replace repeating songs
// here, just so they don't loop forever.
```

2024-04-28 17:13 UTC, wench commented
> Re-enabled the Nighttime track. Before this is ready to be merged, @wench mentioned in #498 that his jukebox egg looping fix also fixes the bee cave outside of this.
> 
> ```
> // Don't override bee cave music with dungeon music.
> 			const bool notbees = !GAME_BG || curr_track != 54;
> if (curr_track == -1 || gwin->is_bg_track(curr_track)
> 				|| (((currentstate == Dungeon && notbees)
> 					 || currentstate == DangerNear)
> 					&& !is_combat_music(curr_track))) {
> ```
> 
> And possibly this TODO, right?
> 
> ```
> // ++++ TODO: Need to come up with a way to replace repeating songs
> // here, just so they don't loop forever.
> ```

Yep, should be fixed by my changes and I noticed that Skara Brae would have the same problem as most of the island is covered by eggs that all play the same music track. In fact i am going to guess the problem exists in lots of places in both games.

2024-04-28 18:04 UTC, DominusExult commented
> Yep, should be fixed by my changes and I noticed that Skara Brae would have the same problem as most of the island is covered by eggs that all play the same music track. In fact i am going to guess the problem exists in lots of places in both games. It wouldn't be reasonable to special case every location but my general looping fix is the right way to do things.

Thanks for fixing this!

So my pull request is ready once #508 is merged

2024-04-28 18:28 UTC, marzojr approved these changes

2024-04-30 11:50 UTC, wench approved these changes

2024-04-30 12:07 UTC, merged

2024-05-01 16:14 UTC, Dragon-Baroque commented
Sorry to come after the commit has been merged.

- I now have some warnings from GCC and CLang about `gamewin.cc` complaining that we may end up sending a random sound effect because neither the day ( at 254 ) nor the night branch ( at 251 ) are taken and that the `int sound;  // SFX#`  at 245 is not setting a value.
So I would like to replace 245 by `int sound = -1; // SFX #`. Not by 0 which is a valid SFX number.

- I would like also to protect the call to `play_sound_effect` and the computation of `repeats` and `delay` at 259..268 by a `if (sound >= 0)`, and place a reset of `repeats` to 0 into an `else` branch.

- I am a bit worried by the case `if (repeats > 0)` at 248. In effect if you are in a daytime _repeat_ the daytime music track check is bypassed and you replay the sound effect, _thus even if a music track started between the first emit of the sound effect and the current repeat_. But I have no good proposal for this.

Now about understanding better the purpose of `Background_noise::handle_event`.

- You expect to produce the  background _music_ tracks 4 RainStorm, 5 SnowStorm, 6 DayTime, 7 NightTime, but only on a faithful MT32 audio device, either using the digital OGGs or using the MT32 library, but not the FMOpl library. And only when no other regular - I mean not background - music tracks are playing.
 
- You expect to produce randomly the 61 Criquet sound effect at night, whether or not the any music track is playing.

- You expect to produce randomly the 82 and 85 Birds sound effects during the day, only when no music track is playing, and not when the audio device is a MT32 like. This is because the DayTime music track 6, already contains bird songs, is it ?

If this is so, I have the following comments to make :

- The test `if (player || play_bg_tracks)` at 187 is wrong, it should be `if (player && play_bg_tracks)`, otherwise the `play_bg_tracks` has no effect.

- The volume `AUDIO_MAX_VOLUME - 200` is very weak. I have tried various settings, using the headphones and the loudspeakers, and I think the setting should not go below `AUDIO_MAX_VOLUME - 32`.

Should I prepare a PR along those lines ?

2024-05-01 17:26 UTC, Dragon-Baroque commented
> I guess the volume is a very subjective thing :) maybe we can compromise on something in between? -50?

I changed to `AUDIO_MAX_VOLUME - 64`.

This is PR #511