Simplify tqueue
exult/exult pull request #96
Opened 2021-03-20 19:51 UTC by alagner

Some code clean-up, mostly moving from bare loops to STL algos/ranged for loops.
I actually wanted to use upper bound in `activate0`, too, but it seems objects are deletign themselves sometimes, which ends in double-free again, so I gave it up, temporarily at least.
@marzojr two questions related to tqueue:
1. What will you say about using a different data structure? As it's supposed to be sorted, multimap with time being the key seems more viable than list. I was also thinking about priority queue, but it does not allow random access.
2. What do you think about including Boost? Some classes like Tqeue could greatly benefit from it, e.g. thanks to its filter_iterator (which currently Tqeue_iteratator replaces). License-wise that should not be a problem, iterator is a header-only lib, question is if we want an extra dependency there.

2021-03-21 12:25 UTC, marzojr requested changes

2021-03-21 12:25 UTC, marzojr commented on tqueue.cc
>  	return 0;         // Not found.
This is dead code.

2021-03-21 12:25 UTC, marzojr commented on tqueue.cc
>  	}
Please avoid using `else` here, as the `if` is just a return. Maybe invert the condition check? See also dead code comment.

2021-03-21 12:25 UTC, marzojr commented on tqueue.cc
> +    return found;
Indenting with spaces instead of tabs.

2021-03-21 18:48 UTC, marzojr approved these changes

2021-03-21 18:48 UTC, merged

2022-02-06 14:02 UTC, DominusExult commented
This is causing regressions in #143 and #140